%YAML:1.0


# general parameters
imu: 1 # if zero we do full 6 dof, otherwise if 1 then 4 dof optimization
output_path: "~/output/" # where to save final trajectory


#loop closure parameters
load_previous_pose_graph: 0 # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1 # save image in pose graph for visualization prupose; you can close this function by setting 0



skip_dist: 0.15 # meters, distance between keyframes
skip_cnt: 0 # num, skip every n frames